const IMPORT_SEED_PHRASE_OPTIONS = "IMPORT_SEED_PHRASE_OPTIONS"
const FRESH_NODE_SETUP = "FRESH_NODE_SETUP"
const FRESH_NODE_LOADING_FOR_KEYS = "FRESH_NODE_LOADING_FOR_KEYS"
const FRESH_NODE_CONNECT_OPTIONS = "FRESH_NODE_CONNECT_OPTIONS"
const FRESH_NODE_ADD_CONNECTIONS = "FRESH_NODE_ADD_CONNECTIONS"
const FRESH_NODE_AUTO_CONNECT = "FRESH_NODE_AUTO_CONNECT"
const FRESH_NODE_WELCOME_TO_THE_NETWORK = "FRESH_NODE_WELCOME_TO_THE_NETWORK";
const FRESH_NODE_SKIP = "FRESH_NODE_SKIP"
const IMPORT_SEED_PHRASE_ENTER_SEED_PHRASE = "IMPORT_SEED_PHRASE_ENTER_SEED_PHRASE"
const IMPORT_SEED_PHRASE_ENTER_SECRET_KEY = "IMPORT_SEED_PHRASE_ENTER_SECRET_KEY"
const IMPORT_SEED_PHRASE_ENTER_CUSTOM_PHRASE = "IMPORT_SEED_PHRASE_ENTER_CUSTOM_PHRASE"
const IMPORT_SEED_PHRASE_NUMBER_OF_KEYS = "IMPORT_SEED_PHRASE_NUMBER_OF_KEYS"
const IMPORT_SEED_PHRASE_KEY_USES = "IMPORT_SEED_PHRASE_KEY_USES"
const IMPORT_SEED_PHRASE_RECOVER_WITH_MEGA_NODE_OPTIONS = "IMPORT_SEED_PHRASE_RECOVER_WITH_MEGA_NODE_OPTIONS"
const IMPORT_SEED_PHRASE_RECOVER_WITH_MEGA_NODE = "IMPORT_SEED_PHRASE_RECOVER_WITH_MEGA_NODE"
const IMPORT_SEED_PHRASE_RECOVER_WITH_MEGA_NODE_MANUALLY = "IMPORT_SEED_PHRASE_RECOVER_WITH_MEGA_NODE_MANUALLY"
const IMPORT_SEED_PHRASE_RECOVER_WITH_MEGA_NODE_AUTO_CONNECT = "IMPORT_SEED_PHRASE_RECOVER_WITH_MEGA_NODE_AUTO_CONNECT"
const IMPORT_SEED_PHRASE_RESTORING_FROM_PHRASE = "IMPORT_SEED_PHRASE_RESTORING_FROM_PHRASE"

const RESTORE_FROM_BACKUP = "RESTORE_FROM_BACKUP"
const RESTORE_FROM_BACKUP_SELECT_FILE = "RESTORE_FROM_BACKUP_SELECT_FILE"
const RESTORE_FROM_BACKUP_PASSWORD = "RESTORE_FROM_BACKUP_PASSWORD"
const RESTORE_FROM_BACKUP_RESTORING = "RESTORE_FROM_BACKUP_RESTORING"

export default {
    FRESH_NODE_WELCOME_TO_THE_NETWORK,
    FRESH_NODE_SETUP,
    FRESH_NODE_LOADING_FOR_KEYS,
    FRESH_NODE_CONNECT_OPTIONS,
    FRESH_NODE_ADD_CONNECTIONS,
    FRESH_NODE_AUTO_CONNECT,
    FRESH_NODE_SKIP,
    IMPORT_SEED_PHRASE_OPTIONS,
    IMPORT_SEED_PHRASE_ENTER_SEED_PHRASE,
    IMPORT_SEED_PHRASE_ENTER_SECRET_KEY,
    IMPORT_SEED_PHRASE_ENTER_CUSTOM_PHRASE,
    IMPORT_SEED_PHRASE_NUMBER_OF_KEYS,
    IMPORT_SEED_PHRASE_KEY_USES,
    IMPORT_SEED_PHRASE_RECOVER_WITH_MEGA_NODE_OPTIONS,
    IMPORT_SEED_PHRASE_RECOVER_WITH_MEGA_NODE,
    IMPORT_SEED_PHRASE_RECOVER_WITH_MEGA_NODE_MANUALLY,
    IMPORT_SEED_PHRASE_RECOVER_WITH_MEGA_NODE_AUTO_CONNECT,
    IMPORT_SEED_PHRASE_RESTORING_FROM_PHRASE,
    RESTORE_FROM_BACKUP,
    RESTORE_FROM_BACKUP_SELECT_FILE,
    RESTORE_FROM_BACKUP_PASSWORD,
    RESTORE_FROM_BACKUP_RESTORING,
}